### ISSUE TITLE
Task timed out

### ISSUE THREAD

**Issue by yureiita** [aws-samples/getting-started-with-amazon-redshift-data-api#6] opened 2022-07-20 08:39 UTC
Hello, we use redshift serverless and I modified the [RedShiftDataAPI.py](https://github.com/aws-samples/getting-started-with-amazon-redshift-data-api/blob/main/quick-start/python/RedShiftDataAPI.py) as below but I always get task timed out even though I've tried increasing the lambda timeout to 3 minutes
```
import time
import traceback
import boto3
import logging
from collections import OrderedDict
from aws_lambda_powertools import Logger

logger = Logger()


def lambda_handler(event, context):
    # input parameters passed from the caller event
    # cluster identifier for the Amazon Redshift cluster
    redshift_workgroup_name = event["redshift_workgroup_name"]
    # database name for the Amazon Redshift cluster
    redshift_database_name = event["redshift_database"]
    # IAM Role of Amazon Redshift cluster having access to S3
    redshift_iam_role = event["redshift_iam_role"]
    # run_type can be either asynchronous or synchronous; try tweaking based on your requirement
    run_type = event["run_type"]

    sql_statements = OrderedDict()
    res = OrderedDict()

    if run_type != "synchronous" and run_type != "asynchronous":
        raise Exception(
            "Invalid Event run_type. \n run_type has to be synchronous or asynchronous."
        )

    isSynchronous = True if run_type == "synchronous" else False

    # initiate redshift-data redshift_data_api_client in boto3
    redshift_data_api_client = boto3.client("redshift-data")

    sql_statements["CREATE"] = (
        "CREATE TABLE IF NOT EXISTS public.region ("
        + "R_REGIONKEY bigint NOT NULL,"
        + "R_NAME varchar(25),"
        + "R_COMMENT varchar(152))"
        + "diststyle all;"
    )
    sql_statements["COPY"] = (
        "COPY public.region FROM 's3://redshift-immersionday-labs/data/region/region.tbl.lzo' "
        + "iam_role '"
        + redshift_iam_role
        + "' region 'us-west-2' lzop delimiter '|' COMPUPDATE PRESET;"
    )
    sql_statements[
        "UPDATE"
    ] = "UPDATE public.region set r_regionkey = 5 where r_name ='AFRICA';"
    sql_statements["DELETE"] = "DELETE From public.region where r_name = 'MIDDLE EAST';"
    sql_statements["SELECT"] = "SELECT r_regionkey,r_name from public.region;"
    logger.info("Running sql queries in {} mode!\n".format(run_type))

    try:
        for command, query in sql_statements.items():
            logging.info("Example of {} command :".format(command))
            res[command + " STATUS: "] = execute_sql_data_api(
                redshift_data_api_client,
                redshift_database_name,
                command,
                query,
                redshift_workgroup_name,
                isSynchronous,
            )

    except Exception as e:
        raise Exception(str(e) + "\n" + traceback.format_exc())
    return res


def execute_sql_data_api(
    redshift_data_api_client,
    redshift_database_name,
    command,
    query,
    redshift_workgroup_name,
    isSynchronous,
):

    MAX_WAIT_CYCLES = 20
    attempts = 0
    # Calling Redshift Data API with executeStatement()
    res = redshift_data_api_client.execute_statement(
        Database=redshift_database_name,
        Sql=query,
        WorkgroupName=redshift_workgroup_name,
    )
    query_id = res["Id"]
    desc = redshift_data_api_client.describe_statement(Id=query_id)
    query_status = desc["Status"]
    logger.info("Query status: {} .... for query-->{}".format(query_status, query))
    done = False

    # Wait until query is finished or max cycles limit has been reached.
    while not done and isSynchronous and attempts < MAX_WAIT_CYCLES:
        attempts += 1
        time.sleep(1)
        desc = redshift_data_api_client.describe_statement(Id=query_id)
        query_status = desc["Status"]

        if query_status == "FAILED":
            raise Exception("SQL query failed:" + query_id + ": " + desc["Error"])

        elif query_status == "FINISHED":
            logger.info(
                "query status is: {} for query id: {} and command: {}".format(
                    query_status, query_id, command
                )
            )
            done = True
            # print result if there is a result (typically from Select statement)
            if desc["HasResultSet"]:
                response = redshift_data_api_client.get_statement_result(Id=query_id)
                logger.info(
                    "Printing response of {} query --> {}".format(
                        command, response["Records"]
                    )
                )
        else:
            logger.info("Current working... query status is: {} ".format(query_status))

    # Timeout Precaution
    if done == False and attempts >= MAX_WAIT_CYCLES and isSynchronous:
        logger.info(
            "Limit for MAX_WAIT_CYCLES has been reached before the query was able to finish. We have exited out of the while-loop. You may increase the limit accordingly. \n"
        )
        raise Exception(
            "query status is: {} for query id: {} and command: {}".format(
                query_status, query_id, command
            )
        )

    return query_status
```

**Comment by Bipin007** [comment] 2022-08-01 15:39
Hi @yureiita - let me try re-generating similar use case on my side, will get back to you shortly.

**Comment by Bipin007** [comment] 2022-08-01 19:54
Hi @yureiita - I can see the execution completes successfully within minute attached is the lambda response. 
Also, please upgrade lambda's boto3 package to latest version as explained here https://www.youtube.com/watch?v=4PiMp7UbKF8

<img width="1547" alt="redshift_lambda_result" src="https://user-images.githubusercontent.com/18270861/182233699-ee398754-eb5d-4fd6-9355-41a18690c9e5.png">

please let us know.

**Comment by Bipin007** [comment] 2022-08-04 17:36
As above query works fine resolving this issue. Please reopen this ticket if the issue is not resolved.

**Closed as completed** 2022-08-04 17:37 UTC
